// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

/** Neon pooler URLs break Prisma Migrate advisory locks (P1002). */
function prismaCliDatabaseUrl(): string {
  const direct = process.env["DIRECT_URL"];
  if (direct) return direct;

  const pooled = process.env["DATABASE_URL"];
  if (!pooled) {
    throw new Error("DATABASE_URL is required for Prisma CLI commands");
  }

  if (pooled.includes("-pooler.")) {
    return pooled.replace("-pooler.", ".");
  }

  return pooled;
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed.ts",
  },
  datasource: {
    url: prismaCliDatabaseUrl(),
  },
});
