services:
  - type: web
    name: torneos-kelme
    runtime: node
    plan: free
    region: oregon
    branch: main
    buildCommand: npm ci --include=dev && npx prisma generate && npx prisma migrate deploy && npm run build
    startCommand: npm start
    healthCheckPath: /login
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: AUTH_SECRET
        generateValue: true
      - key: NEXTAUTH_URL
        sync: false
