import type { BadgeDefinition } from '@/lib/badges/types'

export const BADGE_REGISTRY: BadgeDefinition[] = [
  {
    predicateId: 'gol_ultima_hora',
    name: 'Gol de Última Hora',
    description: 'El gol de la victoria en los minutos finales.',
    family: 'clutch',
    rarity: 'epico',
    iconKey: 'gol_ultima_hora',
    evaluable: true,
    repeatable: true,
    scope: 'match',
    defaultThresholds: { ultimoPct: 15, ganaPor: 1 },
  },
  {
    predicateId: 'heroe_remontada',
    name: 'Héroe de la Remontada',
    description: 'Dio vuelta un partido perdido por 2 o más goles.',
    family: 'clutch',
    rarity: 'legendario',
    iconKey: 'heroe_remontada',
    evaluable: true,
    repeatable: true,
    scope: 'match',
    defaultThresholds: { abajoPor: 2 },
  },
  {
    predicateId: 'mano_helada',
    name: 'Mano Helada',
    description: 'Rompió el empate en el último cuarto.',
    family: 'clutch',
    rarity: 'raro',
    iconKey: 'mano_helada',
    evaluable: true,
    repeatable: true,
    scope: 'match',
    defaultThresholds: { ultimoCuartoPct: 25 },
  },
  {
    predicateId: 'doblete_express',
    name: 'Doblete Exprés',
    description: 'Dos goles en menos de 10 minutos.',
    family: 'clutch',
    rarity: 'epico',
    iconKey: 'doblete_express',
    evaluable: true,
    repeatable: true,
    scope: 'match',
    defaultThresholds: { goles: 2, minutos: 10 },
  },
  {
    predicateId: 'el_ultimo_en_rendirse',
    name: 'El Último en Rendirse',
    description: 'Participó en un gol yendo abajo por 3 o más.',
    family: 'clutch',
    rarity: 'raro',
    iconKey: 'el_ultimo_en_rendirse',
    evaluable: true,
    repeatable: true,
    scope: 'match',
    defaultThresholds: { abajoPor: 3 },
  },
  {
    predicateId: 'hat_trick',
    name: 'Hat-Trick',
    description: 'Tres goles en un partido.',
    family: 'goleador',
    rarity: 'epico',
    iconKey: 'hat_trick',
    evaluable: true,
    repeatable: true,
    scope: 'match',
    defaultThresholds: { goles: 3 },
  },
  {
    predicateId: 'poker',
    name: 'Póker',
    description: 'Cuatro goles o más. Noche perfecta.',
    family: 'goleador',
    rarity: 'legendario',
    iconKey: 'poker',
    evaluable: true,
    repeatable: true,
    scope: 'match',
    defaultThresholds: { goles: 4 },
  },
  {
    predicateId: 'abrio_la_lata',
    name: 'Abrió la Lata',
    description: 'El primer gol del partido.',
    family: 'goleador',
    rarity: 'comun',
    iconKey: 'abrio_la_lata',
    evaluable: true,
    repeatable: true,
    scope: 'match',
    defaultThresholds: {},
  },
  {
    predicateId: 'sentencio',
    name: 'Sentenció',
    description: 'Marcó el gol que dejó diferencia de 3 o más.',
    family: 'goleador',
    rarity: 'comun',
    iconKey: 'sentencio',
    evaluable: true,
    repeatable: true,
    scope: 'match',
    defaultThresholds: { diferencia: 3 },
  },
  {
    predicateId: 'verdugo',
    name: 'Verdugo',
    description: 'Tres goles o más en la misma noche.',
    family: 'goleador',
    rarity: 'raro',
    iconKey: 'verdugo',
    evaluable: true,
    repeatable: true,
    scope: 'match',
    defaultThresholds: { goles: 3 },
  },
  {
    predicateId: 'de_todos_los_sabores',
    name: 'De Todos los Sabores',
    description: 'Gol de zurda, derecha y cabeza en la temporada.',
    family: 'goleador',
    rarity: 'raro',
    iconKey: 'de_todos_los_sabores',
    evaluable: false,
    repeatable: true,
    scope: 'match',
    defaultThresholds: {},
  },
  {
    predicateId: 'arquitecto',
    name: 'El Arquitecto',
    description: 'Tres asistencias en un partido.',
    family: 'creador',
    rarity: 'epico',
    iconKey: 'arquitecto',
    evaluable: true,
    repeatable: true,
    scope: 'match',
    defaultThresholds: { asistencias: 3 },
  },
  {
    predicateId: 'sociedad',
    name: 'Sociedad Anónima',
    description: 'Asistió 3 veces al mismo goleador.',
    family: 'creador',
    rarity: 'raro',
    iconKey: 'sociedad',
    evaluable: true,
    repeatable: true,
    scope: 'match',
    defaultThresholds: { asistencias: 3 },
  },
  {
    predicateId: 'taco_de_oro',
    name: 'Taco de Oro',
    description: 'Gol y asistencia en la misma noche.',
    family: 'creador',
    rarity: 'raro',
    iconKey: 'taco_de_oro',
    evaluable: true,
    repeatable: true,
    scope: 'match',
    defaultThresholds: {},
  },
  {
    predicateId: 'bandeja_de_plata',
    name: 'Bandeja de Plata',
    description: 'Tu primera asistencia de la noche.',
    family: 'creador',
    rarity: 'comun',
    iconKey: 'bandeja_de_plata',
    evaluable: true,
    repeatable: true,
    scope: 'match',
    defaultThresholds: {},
  },
  {
    predicateId: 'valla_invicta',
    name: 'Valla Invicta',
    description: 'El equipo cerró el arco: cero goles en contra.',
    family: 'muralla',
    rarity: 'epico',
    iconKey: 'valla_invicta',
    evaluable: true,
    repeatable: true,
    scope: 'match',
    defaultThresholds: {},
  },
  {
    predicateId: 'muro',
    name: 'El Muro',
    description: 'Ganó recibiendo un gol o menos.',
    family: 'muralla',
    rarity: 'raro',
    iconKey: 'muro',
    evaluable: true,
    repeatable: true,
    scope: 'match',
    defaultThresholds: { golesRecibidosMax: 1 },
  },
  {
    predicateId: 'salvador',
    name: 'San Portero',
    description: 'Atajó un penal.',
    family: 'muralla',
    rarity: 'raro',
    iconKey: 'salvador',
    evaluable: false,
    repeatable: true,
    scope: 'match',
    defaultThresholds: {},
  },
  {
    predicateId: 'pichanga_limpia',
    name: 'Pichanga Limpia',
    description: 'Sin goles en contra en el primer tiempo.',
    family: 'muralla',
    rarity: 'comun',
    iconKey: 'pichanga_limpia',
    evaluable: true,
    repeatable: true,
    scope: 'match',
    defaultThresholds: {},
  },
  {
    predicateId: 'nunca_falla',
    name: 'Nunca Falla',
    description: 'Ocho lunes seguidos en la cancha.',
    family: 'constancia',
    rarity: 'epico',
    iconKey: 'nunca_falla',
    evaluable: true,
    repeatable: true,
    scope: 'match',
    defaultThresholds: { lunesSeguidos: 8 },
  },
  {
    predicateId: 'puntual',
    name: 'Puntual',
    description: 'Cuatro partidos seguidos.',
    family: 'constancia',
    rarity: 'comun',
    iconKey: 'puntual',
    evaluable: true,
    repeatable: true,
    scope: 'match',
    defaultThresholds: { lunesSeguidos: 4 },
  },
  {
    predicateId: 'todoterreno',
    name: 'Todoterreno',
    description: 'Jugó todas las fechas del mes en el club.',
    family: 'constancia',
    rarity: 'raro',
    iconKey: 'todoterreno',
    evaluable: true,
    repeatable: true,
    scope: 'match',
    defaultThresholds: {},
  },
  {
    predicateId: 'el_fundador',
    name: 'De la Vieja Escuela',
    description: '100 partidos en el club. Patrimonio vivo.',
    family: 'constancia',
    rarity: 'legendario',
    iconKey: 'el_fundador',
    evaluable: true,
    repeatable: false,
    scope: 'career',
    defaultThresholds: { partidos: 100 },
  },
  {
    predicateId: 'sin_excusas',
    name: 'Sin Excusas',
    description: 'Jugó bajo lluvia o frío extremo.',
    family: 'constancia',
    rarity: 'raro',
    iconKey: 'sin_excusas',
    evaluable: false,
    repeatable: true,
    scope: 'match',
    defaultThresholds: {},
  },
  {
    predicateId: 'en_contra',
    name: 'Cambio de Camiseta',
    description: 'Se anotó un autogol. Le puede pasar a cualquiera…',
    family: 'camarin',
    rarity: 'comun',
    iconKey: 'en_contra',
    evaluable: true,
    repeatable: true,
    scope: 'match',
    defaultThresholds: {},
  },
  {
    predicateId: 'caballero',
    name: 'Juego Limpio',
    description: 'Temporada completa sin tarjetas.',
    family: 'camarin',
    rarity: 'raro',
    iconKey: 'caballero',
    evaluable: true,
    repeatable: false,
    scope: 'year',
    defaultThresholds: {},
  },
  {
    predicateId: 'tarjetero',
    name: 'Coleccionista de Amarillas',
    description: 'Juntó 3 amarillas en la temporada.',
    family: 'camarin',
    rarity: 'comun',
    iconKey: 'tarjetero',
    evaluable: true,
    repeatable: false,
    scope: 'year',
    defaultThresholds: { amarillas: 3 },
  },
  {
    predicateId: 'el_show',
    name: 'Cara de la Fecha',
    description: 'Fue el MVP del partido.',
    family: 'camarin',
    rarity: 'raro',
    iconKey: 'el_show',
    evaluable: true,
    repeatable: true,
    scope: 'match',
    defaultThresholds: {},
  },
  {
    predicateId: 'bombero',
    name: 'Apaga Incendios',
    description: 'Entró de suplente y dio vuelta la historia.',
    family: 'camarin',
    rarity: 'comun',
    iconKey: 'bombero',
    evaluable: false,
    repeatable: true,
    scope: 'match',
    defaultThresholds: {},
  },
  {
    predicateId: 'club_50',
    name: 'Club de los 50',
    description: 'Cincuenta goles históricos en el club.',
    family: 'hitos',
    rarity: 'epico',
    iconKey: 'club_50',
    evaluable: true,
    repeatable: false,
    scope: 'career',
    defaultThresholds: { goles: 50 },
  },
  {
    predicateId: 'centurion_asist',
    name: 'Centurión',
    description: 'Cincuenta asistencias históricas en el club.',
    family: 'hitos',
    rarity: 'epico',
    iconKey: 'centurion_asist',
    evaluable: true,
    repeatable: false,
    scope: 'career',
    defaultThresholds: { asistencias: 50 },
  },
  {
    predicateId: 'kilometrero',
    name: 'Kilometrero',
    description: 'Veinticinco partidos en el club.',
    family: 'hitos',
    rarity: 'raro',
    iconKey: 'kilometrero',
    evaluable: true,
    repeatable: false,
    scope: 'career',
    defaultThresholds: { partidos: 25 },
  },
  {
    predicateId: 'mano_a_mano',
    name: 'Bandeja de Plata',
    description: 'Registra tu primera asistencia de la noche.',
    family: 'creador',
    rarity: 'comun',
    iconKey: 'mano_a_mano',
    evaluable: false,
    repeatable: true,
    scope: 'match',
    defaultThresholds: {},
  },
  {
    predicateId: 'primer_gol',
    name: 'Se Abrió la Cuenta',
    description: 'Tu primer gol en el club. Bienvenido.',
    family: 'hitos',
    rarity: 'comun',
    iconKey: 'primer_gol',
    evaluable: true,
    repeatable: false,
    scope: 'match',
    defaultThresholds: {},
  },
]

export function getBadgeDefinition(predicateId: string): BadgeDefinition {
  const definition = BADGE_REGISTRY.find((row) => row.predicateId === predicateId)
  if (!definition) {
    throw new Error(`Badge definition not found: ${predicateId}`)
  }
  return definition
}
